AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: pregnancy_coach.app.handler
      Runtime: python3.10
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          GROQ_API_KEY: !Ref GroqApiKey
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Parameters:
  GroqApiKey:
    Type: String
    Description: "The API key for Groq"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"