name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up AWS SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build SAM Application
      run: sam build --use-container

    - name: Deploy SAM Application
      env:
        S3_BUCKET: pregnancy-coach-github-actions
      run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name pregnancy-coach --s3-bucket $S3_BUCKET --capabilities CAPABILITY_IAM
